-d C:\Users\Legion\Desktop\final_udp\impl\gwsynthesis\ov5640_udp_pc.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\Legion\Desktop\final_udp\src\ov5640_udp_pc.cst
-cfg C:\Users\Legion\Desktop\final_udp\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
